# true/false
default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - docker.io/calico/cni:v3.20.6
  - docker.io/calico/pod2daemon-flexvol:v3.20.6
  - docker.io/calico/node:v3.20.6
  - docker.io/calico/kube-controllers:v3.20.6
  - quay-mirror.qiniu.com/coreos/flannel:v0.12.0-s390x
  - docker.io/calico/cni:v3.25.0
  - docker.io/calico/node:v3.25.0
  - docker.io/calico/kube-controllers:v3.25.0
