default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
- goharbor/harbor-log:v2.11.1
- goharbor/registry-photon:v2.11.1
- goharbor/harbor-registryctl:v2.11.1
- goharbor/harbor-db:v2.11.1
- goharbor/harbor-core:v2.11.1
- goharbor/harbor-portal:v2.11.1
- goharbor/harbor-jobservice:v2.11.1
- goharbor/redis-photon:v2.11.1
- goharbor/nginx-photon:v2.11.1
