# true/false
default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - docker.io/calico/cni:v3.23.2
  - docker.io/calico/node:v3.23.2
  - docker.io/calico/kube-controllers:v3.23.2
