# true/false
default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - wangyanglinux/myapp:v1.0
  - wangyanglinux/myapp:v2.0
  - wangyanglinux/myapp:v3.0
  - wangyanglinux/myapp:v4.0
  - wangyanglinux/myapp:v5.0
  - wangyanglinux/myapp:v6.0
  - wangyanglinux/tools:busybox
