default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - quay.io/prometheus/blackbox-exporter:v0.25.0
  - quay.io/prometheus/alertmanager:v0.27.0
  - quay.io/prometheus/prometheus:v2.54.0
  - grafana/grafana:11.1.3
