# true/false
default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - docker.elastic.co/elasticsearch/elasticsearch:7.17.9
  - docker.elastic.co/kibana/kibana:7.17.9
